const departments = [
    { name: "Ring 1", code: "R1" , groupId: ""},
    { name: "Ring 2", code: "R2" , groupId: ""},
    { name: "Secretary", code: "SE" , groupId: ""},
    { name: "Treasurer", code: "TR" , groupId: ""},
    { name: "Entrepreneurship and Household", code: "EH" , groupId: ""},
    { name: "Organizational Controller", code: "OC" , groupId: ""},
    { name: "Product Incubation", code: "PI" , groupId: ""},
    { name: "Technological Studies", code: "TS" , groupId: ""},
    { name: "Career Development", code: "CV" , groupId: ""},
    { name: "Creative Marketing", code: "CM" , groupId: ""},
    { name: "Academic Management", code: "AM" , groupId: ""},
    { name: "Member Welfare", code: "MW" , groupId: ""},
    { name: "Community Development", code: "CD" , groupId: ""},
    { name: "Extracurricular", code: "EC" , groupId: ""},
    { name: "Social Studies", code: "SS" , groupId: ""},
    { name: "Social Movements", code: "SM" , groupId: ""},
    { name: "Intracampus Relation", code: "IR" , groupId: ""},
    { name: "Extracampus Relations", code: "ER" , groupId: ""},
    { name: "Talent Management", code: "TM" , groupId: ""},
    { name: "Project Management", code: "PM" , groupId: ""},
    { name: "Talent Acquisition", code: "TA" , groupId: ""},
    { name: "Talent Development", code: "TD" , groupId: "C1119bsadsad44c7d5b"},
    { name: "Admin Bot", code: "AA", groupId: "C1119bc1221f84a5e9c6fad69b44c7d5b"},
    { name: "Uji Coba 1", code: "AB", groupId: "Cf28f894492f1d7f021cfb9c7ba1dd0b8"},
    { name: "Uji Coba 2", code: "AC", groupId: "Cc36d3f83b2bc760c4af4b8b9e743b9f5"},
    { name: "Uji Coba 3", code: "AD", groupId: "C23a7818321ea5514d8d86c58cb349417"},
  ];
  
  module.exports = { departments };