const departments = [
    { name: "Ring 1", code: "R1" , lineGroupCode: "[RING 1]", groupId: ""},
    { name: "Ring 2", code: "R2" , lineGroupCode: "[RING 2]", groupId: ""},
    { name: "Secretary", code: "SE" , lineGroupCode: "[SE]", groupId: ""},
    { name: "Treasurer", code: "TR" , lineGroupCode: "[TR]", groupId: ""},
    { name: "Entrepreneurship and Household", code: "EH" , lineGroupCode: "[EH]", groupId: ""},
    { name: "Organizational Controller", code: "OC" , lineGroupCode: "[OC]", groupId: ""},
    { name: "Product Incubation", code: "PI" , lineGroupCode: "[PI]", groupId: ""},
    { name: "Technological Studies", code: "TS" , lineGroupCode: "[TS]", groupId: ""},
    { name: "Career Development", code: "CV" , lineGroupCode: "[CV]", groupId: ""},
    { name: "Creative Marketing", code: "CM" , lineGroupCode: "[CM]", groupId: ""},
    { name: "Academic Management", code: "AM" , lineGroupCode: "[AM]", groupId: ""},
    { name: "Member Welfare", code: "MW" , lineGroupCode: "[MW]", groupId: ""},
    { name: "Community Development", code: "CD" , lineGroupCode: "[CD]", groupId: ""},
    { name: "Extracurricular", code: "EC" , lineGroupCode: "[EC]", groupId: ""},
    { name: "Social Studies", code: "SS" , lineGroupCode: "[SS]", groupId: ""},
    { name: "Social Movements", code: "SM" , lineGroupCode: "[SM]", groupId: ""},
    { name: "Intracampus Relation", code: "IR" , lineGroupCode: "[IR]", groupId: ""},
    { name: "Extracampus Relations", code: "ER" , lineGroupCode: "[ER]", groupId: ""},
    { name: "Talent Management", code: "TM" , lineGroupCode: "[TM]", groupId: ""},
    { name: "Project Management", code: "PM" , lineGroupCode: "[PM]", groupId: ""},
    { name: "Talent Acquisition", code: "TA" , lineGroupCode: "[TA]", groupId: ""},
    { name: "Talent Development", code: "TD" , lineGroupCode: "[TD]", groupId: ""},
    { name: "Admin Bot", code: "AA", lineGroupCode: "[AA]", groupId: "C1119bc1221f84a5e9c6fad69b44c7d5b"},
    { name: "Uji Coba 1", code: "AB", lineGroupCode: "[AB]", groupId: "Cf28f894492f1d7f021cfb9c7ba1dd0b8"},
    { name: "Uji Coba 2", code: "AC", lineGroupCode: "[AC]", groupId: "Cc36d3f83b2bc760c4af4b8b9e743b9f5"},
    { name: "Uji Coba 3", code: "AD", lineGroupCode: "[AD]", groupId: "C23a7818321ea5514d8d86c58cb349417"},
  ];
  
  module.exports = { departments };